
function getLongBreakStart() {
    return 6;
}

function getLongBreakEnd() {
    return 17;
}

function getStandard(employeeNum, date) {
    return 8.0;
}

function getUserInfo(badgeNum) {
    return users.find(element => element.Badge == badgeNum);
}
const users = [{
        "UserId": 1,
        "Badge": "5000",
        "AgreementID": 1
    }, {
        "UserId": 2,
        "Badge": "2",
        "AgreementID": 0
    }, {
        "UserId": 3,
        "Badge": "2",
        "AgreementID": 6
    }, {
        "UserId": 4,
        "Badge": "9",
        "AgreementID": 0
    }, {
        "UserId": 5,
        "Badge": "305",
        "AgreementID": 6
    }, {
        "UserId": 6,
        "Badge": "133",
        "AgreementID": 6
    }, {
        "UserId": 7,
        "Badge": "131",
        "AgreementID": 16
    }, {
        "UserId": 8,
        "Badge": "136",
        "AgreementID": 6
    }, {
        "UserId": 9,
        "Badge": "127",
        "AgreementID": 16
    }, {
        "UserId": 10,
        "Badge": "126",
        "AgreementID": 1
    }, {
        "UserId": 11,
        "Badge": "301",
        "AgreementID": 16
    }, {
        "UserId": 12,
        "Badge": "135",
        "AgreementID": 6
    }, {
        "UserId": 13,
        "Badge": "128",
        "AgreementID": 4
    }, {
        "UserId": 14,
        "Badge": "132",
        "AgreementID": 6
    }, {
        "UserId": 15,
        "Badge": "130",
        "AgreementID": 6
    }, {
        "UserId": 16,
        "Badge": "129",
        "AgreementID": 3
    }, {
        "UserId": 17,
        "Badge": "134",
        "AgreementID": 6
    }, {
        "UserId": 18,
        "Badge": "303",
        "AgreementID": 6
    }, {
        "UserId": 19,
        "Badge": "205",
        "AgreementID": 6
    }, {
        "UserId": 20,
        "Badge": "202",
        "AgreementID": 16
    }, {
        "UserId": 21,
        "Badge": "68",
        "AgreementID": 4
    }, {
        "UserId": 22,
        "Badge": "13",
        "AgreementID": 12
    }, {
        "UserId": 23,
        "Badge": "17",
        "AgreementID": 16
    }, {
        "UserId": 24,
        "Badge": "22",
        "AgreementID": 16
    }, {
        "UserId": 25,
        "Badge": "28",
        "AgreementID": 16
    }, {
        "UserId": 26,
        "Badge": "29",
        "AgreementID": 16
    }, {
        "UserId": 27,
        "Badge": "92",
        "AgreementID": 16
    }, {
        "UserId": 28,
        "Badge": "60",
        "AgreementID": 6
    }, {
        "UserId": 29,
        "Badge": "85",
        "AgreementID": 6
    }, {
        "UserId": 30,
        "Badge": "69",
        "AgreementID": 16
    }, {
        "UserId": 31,
        "Badge": "83",
        "AgreementID": 6
    }, {
        "UserId": 32,
        "Badge": "73",
        "AgreementID": 16
    }, {
        "UserId": 33,
        "Badge": "74",
        "AgreementID": 4
    }, {
        "UserId": 34,
        "Badge": "78",
        "AgreementID": 4
    }, {
        "UserId": 35,
        "Badge": "84",
        "AgreementID": 16
    }, {
        "UserId": 36,
        "Badge": "47",
        "AgreementID": 16
    }, {
        "UserId": 37,
        "Badge": "80",
        "AgreementID": 6
    }, {
        "UserId": 38,
        "Badge": "26",
        "AgreementID": 16
    }, {
        "UserId": 39,
        "Badge": "91",
        "AgreementID": 6
    }, {
        "UserId": 40,
        "Badge": "89",
        "AgreementID": 6
    }, {
        "UserId": 41,
        "Badge": "90",
        "AgreementID": 6
    }, {
        "UserId": 42,
        "Badge": "4",
        "AgreementID": 1
    }, {
        "UserId": 43,
        "Badge": "201",
        "AgreementID": 6
    }, {
        "UserId": 44,
        "Badge": "70",
        "AgreementID": 6
    }, {
        "UserId": 45,
        "Badge": "307",
        "AgreementID": 16
    }, {
        "UserId": 46,
        "Badge": "40",
        "AgreementID": 0
    }, {
        "UserId": 47,
        "Badge": "587",
        "AgreementID": 0
    }, {
        "UserId": 48,
        "Badge": "321",
        "AgreementID": 6
    }, {
        "UserId": 49,
        "Badge": "324",
        "AgreementID": 6
    }, {
        "UserId": 50,
        "Badge": "323",
        "AgreementID": 3
    }, {
        "UserId": 51,
        "Badge": "350",
        "AgreementID": 13
    }, {
        "UserId": 52,
        "Badge": "349",
        "AgreementID": 4
    }, {
        "UserId": 53,
        "Badge": "360",
        "AgreementID": 16
    }, {
        "UserId": 54,
        "Badge": "344",
        "AgreementID": 6
    }, {
        "UserId": 55,
        "Badge": "346",
        "AgreementID": 4
    }, {
        "UserId": 56,
        "Badge": "343",
        "AgreementID": 6
    }, {
        "UserId": 57,
        "Badge": "341",
        "AgreementID": 6
    }, {
        "UserId": 58,
        "Badge": "93",
        "AgreementID": 1
    }, {
        "UserId": 59,
        "Badge": "79",
        "AgreementID": 16
    }, {
        "UserId": 60,
        "Badge": "347",
        "AgreementID": 16
    }, {
        "UserId": 61,
        "Badge": "348",
        "AgreementID": 6
    }, {
        "UserId": 62,
        "Badge": "342",
        "AgreementID": 6
    }, {
        "UserId": 63,
        "Badge": "322",
        "AgreementID": 6
    }, {
        "UserId": 64,
        "Badge": "990",
        "AgreementID": 6
    }, {
        "UserId": 65,
        "Badge": "362",
        "AgreementID": 16
    }, {
        "UserId": 66,
        "Badge": "364",
        "AgreementID": 4
    }, {
        "UserId": 67,
        "Badge": "177",
        "AgreementID": 6
    }, {
        "UserId": 68,
        "Badge": "323",
        "AgreementID": 6
    }, {
        "UserId": 69,
        "Badge": "347999",
        "AgreementID": 0
    }, {
        "UserId": 70,
        "Badge": "9",
        "AgreementID": 6
    }, {
        "UserId": 71,
        "Badge": "370",
        "AgreementID": 0
    }, {
        "UserId": 72,
        "Badge": "370",
        "AgreementID": 6
    }, {
        "UserId": 73,
        "Badge": "376",
        "AgreementID": 16
    }, {
        "UserId": 74,
        "Badge": "375",
        "AgreementID": 6
    }, {
        "UserId": 75,
        "Badge": "377",
        "AgreementID": 6
    }, {
        "UserId": 76,
        "Badge": "40",
        "AgreementID": 6
    }, {
        "UserId": 77,
        "Badge": "382",
        "AgreementID": 16
    }, {
        "UserId": 78,
        "Badge": "385",
        "AgreementID": 4
    }, {
        "UserId": 79,
        "Badge": "386",
        "AgreementID": 4
    }, {
        "UserId": 80,
        "Badge": "392",
        "AgreementID": 6
    }, {
        "UserId": 81,
        "Badge": "387",
        "AgreementID": 6
    }, {
        "UserId": 82,
        "Badge": "391",
        "AgreementID": 6
    }, {
        "UserId": 83,
        "Badge": "393",
        "AgreementID": 6
    }, {
        "UserId": 84,
        "Badge": "388",
        "AgreementID": 16
    }, {
        "UserId": 85,
        "Badge": "394",
        "AgreementID": 16
    }, {
        "UserId": 86,
        "Badge": "396",
        "AgreementID": 16
    }, {
        "UserId": 87,
        "Badge": "397",
        "AgreementID": 16
    }, {
        "UserId": 88,
        "Badge": "0",
        "AgreementID": 6
    }, {
        "UserId": 89,
        "Badge": "398",
        "AgreementID": 4
    }, {
        "UserId": 90,
        "Badge": "436",
        "AgreementID": 6
    }, {
        "UserId": 91,
        "Badge": "399",
        "AgreementID": 6
    }, {
        "UserId": 92,
        "Badge": "402",
        "AgreementID": 6
    }, {
        "UserId": 93,
        "Badge": "406",
        "AgreementID": 3
    }, {
        "UserId": 94,
        "Badge": "405",
        "AgreementID": 3
    }, {
        "UserId": 95,
        "Badge": "407",
        "AgreementID": 6
    }, {
        "UserId": 96,
        "Badge": "931",
        "AgreementID": 0
    }, {
        "UserId": 97,
        "Badge": "470",
        "AgreementID": 6
    }, {
        "UserId": 98,
        "Badge": "981",
        "AgreementID": 0
    }, {
        "UserId": 99,
        "Badge": "40",
        "AgreementID": 0
    }, {
        "UserId": 100,
        "Badge": "417",
        "AgreementID": 6
    }, {
        "UserId": 101,
        "Badge": "40",
        "AgreementID": 0
    }, {
        "UserId": 102,
        "Badge": "418",
        "AgreementID": 6
    }, {
        "UserId": 103,
        "Badge": "605",
        "AgreementID": 0
    }, {
        "UserId": 104,
        "Badge": "642",
        "AgreementID": 0
    }, {
        "UserId": 105,
        "Badge": "931",
        "AgreementID": 0
    }, {
        "UserId": 106,
        "Badge": "40",
        "AgreementID": 0
    }, {
        "UserId": 107,
        "Badge": "291",
        "AgreementID": 0
    }, {
        "UserId": 108,
        "Badge": "421",
        "AgreementID": 4
    }, {
        "UserId": 109,
        "Badge": "423",
        "AgreementID": 16
    }, {
        "UserId": 110,
        "Badge": "422",
        "AgreementID": 6
    }, {
        "UserId": 111,
        "Badge": "291",
        "AgreementID": 3
    }, {
        "UserId": 112,
        "Badge": "426",
        "AgreementID": 4
    }, {
        "UserId": 113,
        "Badge": "425",
        "AgreementID": 6
    }, {
        "UserId": 114,
        "Badge": "428",
        "AgreementID": 6
    }, {
        "UserId": 115,
        "Badge": "429",
        "AgreementID": 6
    }, {
        "UserId": 116,
        "Badge": "426",
        "AgreementID": 4
    }, {
        "UserId": 117,
        "Badge": "432",
        "AgreementID": 4
    }, {
        "UserId": 118,
        "Badge": "40",
        "AgreementID": 0
    }, {
        "UserId": 119,
        "Badge": "40",
        "AgreementID": 0
    }, {
        "UserId": 120,
        "Badge": "66",
        "AgreementID": 0
    }, {
        "UserId": 121,
        "Badge": "339",
        "AgreementID": 0
    }, {
        "UserId": 122,
        "Badge": "434",
        "AgreementID": 6
    }, {
        "UserId": 123,
        "Badge": "339",
        "AgreementID": 0
    }, {
        "UserId": 124,
        "Badge": "121",
        "AgreementID": 0
    }, {
        "UserId": 125,
        "Badge": "441",
        "AgreementID": 6
    }, {
        "UserId": 126,
        "Badge": "442",
        "AgreementID": 6
    }, {
        "UserId": 127,
        "Badge": "339",
        "AgreementID": 0
    }, {
        "UserId": 128,
        "Badge": "443",
        "AgreementID": 16
    }, {
        "UserId": 129,
        "Badge": "444",
        "AgreementID": 16
    }, {
        "UserId": 130,
        "Badge": "446",
        "AgreementID": 6
    }, {
        "UserId": 131,
        "Badge": "445",
        "AgreementID": 16
    }, {
        "UserId": 132,
        "Badge": "447",
        "AgreementID": 6
    }, {
        "UserId": 133,
        "Badge": "406",
        "AgreementID": 0
    }, {
        "UserId": 134,
        "Badge": "448",
        "AgreementID": 16
    }, {
        "UserId": 135,
        "Badge": "383",
        "AgreementID": 16
    }, {
        "UserId": 136,
        "Badge": "450",
        "AgreementID": 16
    }, {
        "UserId": 137,
        "Badge": "449",
        "AgreementID": 4
    }, {
        "UserId": 138,
        "Badge": "451",
        "AgreementID": 16
    }, {
        "UserId": 139,
        "Badge": "507",
        "AgreementID": 0
    }, {
        "UserId": 140,
        "Badge": "507",
        "AgreementID": 0
    }, {
        "UserId": 141,
        "Badge": "458",
        "AgreementID": 4
    }, {
        "UserId": 142,
        "Badge": "457",
        "AgreementID": 4
    }, {
        "UserId": 143,
        "Badge": "459",
        "AgreementID": 16
    }, {
        "UserId": 144,
        "Badge": "792",
        "AgreementID": 0
    }, {
        "UserId": 145,
        "Badge": "507",
        "AgreementID": 0
    }, {
        "UserId": 146,
        "Badge": "551",
        "AgreementID": 16
    }, {
        "UserId": 147,
        "Badge": "552",
        "AgreementID": 16
    }, {
        "UserId": 148,
        "Badge": "553",
        "AgreementID": 4
    }, {
        "UserId": 149,
        "Badge": "554",
        "AgreementID": 16
    }, {
        "UserId": 150,
        "Badge": "442",
        "AgreementID": 0
    }, {
        "UserId": 151,
        "Badge": "449",
        "AgreementID": 0
    }, {
        "UserId": 152,
        "Badge": "515",
        "AgreementID": 6
    }, {
        "UserId": 153,
        "Badge": "555",
        "AgreementID": 16
    }, {
        "UserId": 154,
        "Badge": "556",
        "AgreementID": 4
    }, {
        "UserId": 155,
        "Badge": "557",
        "AgreementID": 15
    }, {
        "UserId": 156,
        "Badge": "558",
        "AgreementID": 16
    }, {
        "UserId": 157,
        "Badge": "559",
        "AgreementID": 16
    }, {
        "UserId": 158,
        "Badge": "507",
        "AgreementID": 16
    }, {
        "UserId": 159,
        "Badge": "561",
        "AgreementID": 16
    }, {
        "UserId": 160,
        "Badge": "563",
        "AgreementID": 16
    }, {
        "UserId": 161,
        "Badge": "990",
        "AgreementID": 0
    }, {
        "UserId": 162,
        "Badge": "568",
        "AgreementID": 16
    }, {
        "UserId": 163,
        "Badge": "566",
        "AgreementID": 16
    }, {
        "UserId": 164,
        "Badge": "567",
        "AgreementID": 16
    }, {
        "UserId": 165,
        "Badge": "563",
        "AgreementID": 0
    }, {
        "UserId": 166,
        "Badge": "569",
        "AgreementID": 6
    }, {
        "UserId": 167,
        "Badge": "571",
        "AgreementID": 6
    }, {
        "UserId": 168,
        "Badge": "570",
        "AgreementID": 6
    }, {
        "UserId": 169,
        "Badge": "573",
        "AgreementID": 6
    }, {
        "UserId": 170,
        "Badge": "572",
        "AgreementID": 6
    }, {
        "UserId": 171,
        "Badge": "550",
        "AgreementID": 0
    }, {
        "UserId": 172,
        "Badge": "574",
        "AgreementID": 6
    }, {
        "UserId": 173,
        "Badge": "575",
        "AgreementID": 6
    }, {
        "UserId": 174,
        "Badge": "557",
        "AgreementID": 0
    }, {
        "UserId": 175,
        "Badge": "874",
        "AgreementID": 0
    }, {
        "UserId": 176,
        "Badge": "550",
        "AgreementID": 0
    }, {
        "UserId": 177,
        "Badge": "550",
        "AgreementID": 0
    }, {
        "UserId": 178,
        "Badge": "550",
        "AgreementID": 6
    }, {
        "UserId": 179,
        "Badge": "545",
        "AgreementID": 0
    }, {
        "UserId": 180,
        "Badge": "573",
        "AgreementID": 0
    }, {
        "UserId": 181,
        "Badge": "557",
        "AgreementID": 0
    }, {
        "UserId": 182,
        "Badge": "396",
        "AgreementID": 0
    }, {
        "UserId": 183,
        "Badge": "445",
        "AgreementID": 0
    }, {
        "UserId": 184,
        "Badge": "459",
        "AgreementID": 0
    }, {
        "UserId": 185,
        "Badge": "561",
        "AgreementID": 0
    }, {
        "UserId": 186,
        "Badge": "576",
        "AgreementID": 16
    }, {
        "UserId": 187,
        "Badge": "577",
        "AgreementID": 16
    }, {
        "UserId": 188,
        "Badge": "459",
        "AgreementID": 0
    }, {
        "UserId": 189,
        "Badge": "557",
        "AgreementID": 0
    }, {
        "UserId": 190,
        "Badge": "580",
        "AgreementID": 6
    }, {
        "UserId": 191,
        "Badge": "545",
        "AgreementID": 0
    }, {
        "UserId": 192,
        "Badge": "581",
        "AgreementID": 6
    }, {
        "UserId": 193,
        "Badge": "569",
        "AgreementID": 0
    }, {
        "UserId": 194,
        "Badge": "545",
        "AgreementID": 0
    }, {
        "UserId": 195,
        "Badge": "136",
        "AgreementID": 0
    }, {
        "UserId": 196,
        "Badge": "843",
        "AgreementID": 0
    }, {
        "UserId": 197,
        "Badge": "578",
        "AgreementID": 6
    }, {
        "UserId": 198,
        "Badge": "579",
        "AgreementID": 6
    }, {
        "UserId": 199,
        "Badge": "545",
        "AgreementID": 0
    }
]
